name: Build GymRest APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Permissão Gradlew
        run: chmod +x GymRest/gradlew

      - name: Build APK
        run: |
          cd GymRest
          ./gradlew assembleDebug --stacktrace
