name: Build GymRest APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Permissão Gradlew
        run: chmod +x GymRest/gradlew

      - name: Build APK
        run: |
          cd GymRest
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GymRest-debug-apk
          path: GymRest/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
